### ISSUE TITLE
use logic_to_physic when specified in .idx file

### ISSUE THREAD

**Issue by cchriste** [sci-visus/OpenVisus#29]
While logic_to_physic has been deprecated in favor of utilizing transforms specified in .xidx, it's still present in many existing .idx datasets and should continue to be honored since it is part of version 6 idx files. This is necessary since these datasets may not be able to be modified due to permissions or because they are hosted by an older version of the mod_visus server.

```
Example dataset (field highlighted with ***):
(version)
6
***
(logic_to_physic)
1.875 0 0 0 0 1.25 0 0 0 0 1 0 0 0 0 1
***
(box)
0 191 0 144 0 0 0 0 0 0
(fields)
tas float32 compressed format(0) 
+ pr float32 compressed format(0) 
+ huss float32 compressed format(0) 
+ psl float32 compressed format(0) 
+ tasmin float32 compressed format(0) 
+ tasmax float32 compressed format(0) 
(bits)
V0101010101010101
(bitsperblock)
16
(blocksperfile)
1
(interleave block)
0
(time)
time%05d/ (0,0,1) (0,52559,1) 
(filename_template)
./visus/%01x.bin
```

**Comment by scrgiorgio** [comment]
I agree about the " should continue to be honored since it is part of version 6 idx file" .

The problem about the old `logic_to_physic` was the replicated code: (*) one piece was in IDX classes (*) the other piece was (and is) in MIDX classes.

For Alessandra microscopy and VisusSlam, we needed the `generalization of matrices`. In the old version:

(*) all the IDXs were requested to be in the same 'position'
(*) we didn't have the mosaic feature
(*) we didn't have a way to blend borders like we do now with Voronoi expression

So I had to remove the IDX `logic_to_physic`.

Back to your problem: not a long time ago we were discussing about automatically opening an MIDX (or any new format Steve has in mind) even if the file was an IDX. 

Would it work? If so, I need to fully study what implications will be, but I can work in the middle term on that.

Let me know.

**Comment by cchriste** [comment]
Regarding Steve's question, we really need to continue support for
(logic_to_physic) in the .idx files that exist at several locations,
including SCI and LLNL. We do not always have write permission to
automatically upgrade these, so Giorgio's idea sounds good (if I understand
correctly what he's suggesting): just auto-convert in memory the .idx to an
.midx.

I was not aware of the blending issue, but that seems concerning. If it is
decided that the best path forward is to just drop support for existing
.idx files w/ logic_to_physic, I can try to hack something to fix the ones
that I encounter, copying them to a /tmp directory if I don't have access
to the original paths to create an midx. The biggest challenge with that is
guessing which idx files have the logic_to_physic.

The immediate issue is that most of the climate datasets are not
"map-shaped" and require logic_to_physic. I can write a script to search
and attempt to replace all these with midx files, but I'm not super stoked
to spend a day on this if it's possible to auto-convert.

Steve's recommendation of continuing versions and backwards compatibility
is something I agree we should prioritize.

Thanks!

**Comment by cchriste** [comment]
I think this has been fixed since climate datasets seem to be correctly scaled now (but I might just be loading versions with intrinsically correct scales). Can we please confirm and close this issue if so?

**Comment by scrgiorgio** [comment]
I wish it was fixed, but i don't think so

Il giorno mar 5 mar 2019 alle ore 16:32 Cameron Christensen <
notifications@github.com> ha scritto:

**Comment by scrgiorgio** [comment]
Hi Cameron, it's absolutely doable but if you need it for your defence I'm
not positive I will be in time.  Cannot you switch to midx just as backup
solution?

Il mar 28 mag 2019, 18:31 Cameron Christensen <notifications@github.com> ha
scritto:

**Comment by cchriste** [comment]
Thank you for getting back to me about this.
I will make do with what we have for the defense (the server at LLNL is
broken today anyway...).

**Comment by scrgiorgio** [comment]
Let me know how I can help for llnl problem ... I can postpone all other
deadline if needed

Il mar 28 mag 2019, 21:51 Cameron Christensen <notifications@github.com> ha
scritto:
