### ISSUE TITLE
SharedPtr define in namespace

### ISSUE THREAD

**Issue by ptbremer** [sci-visus/OpenVisus#61]
In the latest master we use

#define SharedPtr std::shared_ptr

But in the downstream code I usually try to avoid a 
using namespace Visus; 
to avoid polluting my namespace 

Instead, I think the more correct usage (I think) is 

Visus::SharedPtr<Foo> pFoo;

But this now lead to an error on my system. 

 error: no member named 'std' in namespace 'Visus'; did you mean simply 'std'?

The reason is that we are using a #define rather than a typedef which means that my statement get expanded into 

Visus::std::SharedPtr<Foo> pFoo; 

which does not compile. 

I propose to simply switch to a typedef in Kernel.h, i.e. 

typedef SharedPtr std::shared_ptr;

which should fix this

**Comment by scrgiorgio** [comment]
it's not possible to use a typedef because it's a template class (i.e. a
type does not exists until fully specified using <>).
But fortunately we can use C++11 alias templates (already committed to
GitHub):

#if SWIG



  #define SharedPtr std::shared_ptr

  #define UniquePtr std::unique_ptr



#else



  *//*https://en.cppreference.com/w/cpp/language/type_alias

  *template*<*class* T>

  *using* SharedPtr = std::shared_ptr<T>;



  *template*<*class* T>

  *using* UniquePtr = std::unique_ptr<T>;



#endif


Timo, does it solve the problem?

**Comment by ptbremer** [comment]
Yes this compiles
